image: node:latest

cache:
  paths:
    - node_modules/

before_script:
 - mkdir -p ~/.ssh
	- echo -e "$DEPLOY_KEY" > ~/.ssh/id_rsa
	- chmod 600 ~/.ssh/id_rsa
	- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm install
  only:
    - master

build:
  stage: build
  script:
    - npm install -g @angular/cli
    - ./node_modules/.bin/ng build -prod
  only:
    - master

deploy:
  stage: deploy
  script:
    - ssh root@164.132.226.137 "
      pwd
    "
  only:
    - master
