image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm install
  only:
    - master

build:
  stage: build
  script:
    - npm install -g @angular/cli
    - ./node_modules/.bin/ng build -prod
  only:
    - master

deploy:
  stage: deploy
  
  before_script:
            - mkdir -p ~/.ssh
            - echo -e "$DEPLOY_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        
        script:
            - ssh user@server-name.com "
                cd /var/www/ &&
                php artisan down &&
                git checkout . &&
                git checkout master &&
                git pull &&
                composer install &&
                php artisan migrate &&
                php artisan up
            "
                                    
        environment:
            name: production
            
        only:
            - master
