image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy


deploy:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass

  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod
    - cd dist/
    - ls
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -p 'Mbxfd1Wm' ssh -o StrictHostKeyChecking=no root@164.132.226.137 "cd /root/juniorviec/juniorviec-web"
  environment: staging
  only:
    - master
