image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm install
  only:
    - master

build:
  stage: build
  script:
    - npm install -g @angular/cli
    - ./node_modules/.bin/ng build -prod
  only:
    - master

deploy:
  stage: deploy
  script:
    - ssh root@164.132.226.137 "cd juniorviec/juniorviec-web/ &&
        git checkout master &&
        git fetch &&
        "
  environment: staging
  only:
    - master
