image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy


deploy:
  stage: deploy
  script:
    - ssh root@164.132.226.137 "cd juniorviec/juniorviec-web/ &&
        git checkout master &&
        git fetch &&
        pwd
        "
  environment: staging
  only:
    - master
